### ISSUE TITLE
Changes to model and compatibility with Stockfish

### ISSUE THREAD

**Issue by adalsteinnpals** [glinscott/nnue-pytorch#161]
Seeking advice

I'm experimenting with various NNUE architecture, e.g. without psqt and layer stack buckets, and another feature set than is currently implemented in Stockfish. But leaving the layer stack untouched, only changing the hyperparameters.

The goal is to benchmark it with c-chess-cli (similarly as is done in run_games.py)
I'm wondering if I'm missing some low hanging fruit way of doing that, other than doing considerable amount of changes to Stockfish

All the best,

**Comment by Sopel97** [comment]
If your architecture is compatible with some older version of stockfish you can use that. Otherwise the easiest approach would be to find the closest one and make the necessary changes. Sounds like you could start from Stockfish 12 and possibly change the feature set implementation, if even necessary. For testing you can use any baseline you want.

**Comment by adalsteinnpals** [comment]
Great, thank you for the advice.
